=  Yada Framework
:docinfo: shared

NOTE: Chat with this documentation in the https://chatgpt.com/g/g-IZTpvHTYM-yada-framework-manual[Yada Framework Manual^] custom GPT. Beware of hallucinations!

==  General Principles

Git repository: https://github.com/xtianus/yadaframework

The *Yada Framework* is a collection of libraries, patterns, tools, code snippets and best practices to speed up web site
development.
The main focus is on *productivity* and the approach is to use proven and known technologies
in a repeatable way, so that each new project is easier to develop and maintain.
Another goal is *simplicity* as defined by the KISS principle: some technology that is very powerful and exciting and
complicated to use, won't find a place here.

The technology stack is as follows:

* https://www.oracle.com/java/technologies/javase-downloads.html[Java^]
* https://tomcat.apache.org/download-80.cgi[Tomcat^]
* https://docs.spring.io/spring-framework/docs/current/reference/html/web.html[Spring Web MVC^]
* https://dev.mysql.com/downloads/mysql/[MySQL Community Server^]
* https://hibernate.org/orm/[Hibernate ORM^]
* https://www.thymeleaf.org/[Thymeleaf^]
* https://jquery.com/[jQuery^]
* Javascript
* HTML, CSS, https://sass-lang.com/[SASS^]

Tools used:

* https://www.eclipse.org/downloads/[Eclipse IDE^]
* https://gradle.org/[Gradle^]
* https://git-scm.com/[git^]
* https://asciidoctor.org/[Asciidoctor^]

It is our strong belief that productivity is increased when using old and proven technologies (less bugs,
less chance of deprecation, more documentation, more tools, more developer experience), and that
simple architectures can efficiently solve most practical problems a developer will ever have to face.

==  Documentation Chapters

The documentation is a mix of tutorial and reference. The tutorial loosely follows the official
Java https://eclipse-ee4j.github.io/jakartaee-tutorial/dukes-bookstore.html["Duke’s Bookstore Case Study Example"^] with many improvements in functionality.

[.bookstore]
--
The tutorial sections are shown using this visual style.
--

[NOTE]
====
What follows is a partial list of chapters with a brief explanation. The most
updated index is in the dropdown at the top of each page.
====

<<newEclipseProject.adoc#,Getting Started>>:: This section will guide you through the setup of the development environment: installing Java, git,
MySQL, Eclipse. It will then show you how to create an Eclipse project with a database and a web server

<<examples/bookstoreTutorial.adoc#,Bookstore Tutorial>>:: When your development environment has
been set by following the instructions in the previous chapter, you can start this tutorial
that will show you how to quickly create a web application

<<internationalization.adoc#,i18n>>:: Implement a multilanguage site

<<database/overview.adoc#,Databases>>:: Storing and retrieving data

<<forms/overview.adoc#Forms,Forms>>:: Submitting data to the server

<<ajax.adoc#,Ajax>>:: Easy async operations

<<ajaxModal.adoc#,Ajax Modals>>:: Open a modal as a result of an ajax call

<<security/overview.adoc#,Security>>:: User accounts and protecting pages behind login

<<datatables.adoc#,DataTables>>:: Effective handling of tabular data

<<emails.adoc#,Sending Emails>>:: Templating applied to emails

<<confirmationModal.adoc#,Confirmation Modal>>:: Easily ask for confirmation

<<notificationModal.adoc#,Notification Modal>>:: Quick messages to the user

<<misc.adoc#,Miscellaneous>>:: Other features

<<troubleshooting.adoc#,Troubleshooting>>:: Some hints for fixing problems

<<upgrade.adoc#,Upgrade Yada Framework Version>>:: New versions are announced on this page, together
with instructions on how to migrate from the previous one

==  Current Status
The Yada Framework will always be a work in progress: open source libraries will evolve,
our ways of using them will improve, the Yada code will get smarter, best practices will change,
bugs will be fixed... and documentation will always lag behind.

The master branch in the git repository contains the latest "unstable" development.
Each new stable version will have its own branch on which non-disruptive changes will be committed.
Users, when starting the development of a new project, should pick the latest version on a branch and stick to it.
Every new version might have breaking changes so you should upgrade only when you know you can afford the time of
fixing your code.

A step-by-step guide on how to migrate from a version to the next will be provided <<upgrade.adoc#,here>>.






