=  Yada Framework
:docinfo: shared

==  General Principles
The *Yada Framework* is a collection of libraries, patterns, tools, code snippets and best practices to speed up web site
development.
The main focus is on *productivity* and the approach is to use proven and known technologies
in a repeatable way, so that each new project is easier to develop and maintain.
Another goal is *simplicity* as defined by the KISS principle. If something is very powerful and exciting and
complicated to use, it won't find a place here.

The technology stack is as follows:

* java
* Tomcat
* Spring WebMVC
* MySQL
* Hibernate
* Thymeleaf
* HTML/CSS
* Javascript
* jQuery

Tools used:

* Eclipse
* Gradle
* Asciidoctor

You may think that some are old or obsolete technologies,
but for the purpose of increasing productivity, there's nothing better than something that has been around for years or decades and
is still being used and maintained: developers will spend less time around bugs, architects will know when to use what,
testers will have plenty of tools at their disposal.

[.todo]
----
TO BE CONTINUED...
----


==  Documentation Contents

<<newEclipseProject.adoc#,New Eclipse Project>>:: This section will guide you through the setup of the development environment: installing Java, git,
MySQL, Eclipse. It will then show you how to create an Eclipse project with a database and a web server.

<<internationalization.adoc#>>:: This section shows how easy it is to cope for different languages

<<database/pagination.adoc#>>:: TODO

<<forms/overview.adoc#Forms,Forms>>:: TODO

<<ajax.adoc#>>:: TODO

<<ajaxModal.adoc#>>:: TODO

<<datatables.adoc#>>:: TODO

<<emails.adoc#>>:: TODO

<<internationalization.adoc#>>:: TODO

<<notificationModal.adoc#>>:: TODO

<<troubleshooting.adoc#>>:: TODO


[.todo]
----
TO BE CONTINUED...
----


