=  Misc
:docinfo: shared

Miscellaneous features


==  Client Timezone
The timezone of the user is retrieved via javascript on first page load and sent to the server
for storage in the HTTP Session. This is done via an ajax call at each new browser session.
The timezone for unlogged users can be retrieved from the `YadaConstants.SESSION_USER_TIMEZONE` session
attribute:

[source,java]
----
TimeZone userTimezone = (TimeZone) session.getAttribute(YadaConstants.SESSION_USER_TIMEZONE);
----

On user registration, the timezone is stored in the YadaRegistrationRequest and later in the YadaUserProfile
when registration is confirmed. It is also refreshed at each user login so that it is always up to date.
It can therefore be retrieved with

[source,java]
----
TimeZone userTimezone = userProfile.getTimezone();
----

This feature is totally transparent to the user.
For use cases where the user must be allowed to set the timezone explicitly, the `YadaUtil.getTimezones()` method
can be used to retrieve a list of readable timezones to present in a select. When the user sends the
chosen timezone to the server, the `yadaUserProfile.timezoneSetByUser` flag should be set to true in order
to prevent the default automatic timezone change on login.
For example:

[source,java]
----
if (!formBean.getTimezoneId().equals(userProfile.getTimezone().getID())) {
	// If the timezone is different from before, set the flag
	userProfile.setTimezoneSetByUser(true);
}
userProfile.setTimezone(TimeZone.getTimeZone(formBean.getTimezoneId()));
----
 



