=  Security
:docinfo: shared

Authentication and Authorization: create users, handle login, protect pages


==  Description

The Yada Framework uses Spring Security to implement authentication
(identifying the current user) and authorization (limiting access to web pages 
according to the user role). The YadaWebSecurity library must be added to the classpath
in order for this to work.

==  Setup

The `WebConfig` class must extend `YadaWebSecurityConfig` instead of `YadaWebConfig`:

[source,java]
----
@ComponentScan(basePackages = { "com.example.web" })
public class WebConfig extends YadaWebSecurityConfig {
----

The required YadaWebSecurity entities must also be added to `persistence.xml` in order to create the DB schema:

[source,xml]
----
<persistence-unit name="yadaPersistenceUnit">
	<class>net.yadaframework.security.persistence.entity.YadaSocialCredentials</class>
	<class>net.yadaframework.security.persistence.entity.YadaUserCredentials</class>
	<class>net.yadaframework.security.persistence.entity.YadaUserProfile</class>
	<class>net.yadaframework.security.persistence.entity.YadaRegistrationRequest</class>
	<class>net.yadaframework.security.persistence.entity.YadaAutoLoginToken</class>
----

Some security parameters must be configured in `conf.webapp.prod.xml`:

[source,xml]
----
<config>
	<security>
		<sessionTimeoutMinutes>240</sessionTimeoutMinutes> # <1>
		<passwordLength min='5' max='128' /> # <2>
		<encodePassword>true</encodePassword> # <3>
		<maxFailedAttempts>10</maxFailedAttempts> # <4>
		<failedAttemptsLockoutMinutes>10</failedAttemptsLockoutMinutes> # <5>
		<autologinExpirationHours>48</autologinExpirationHours> # <6>
		<roles> # <7>
			<role>
				<id>8</id>
				<key>ADMIN</key>
			</role>
			<role>
				<id>2</id>
				<key>USER</key>
			</role>
		</roles>
	</security>
----
<1> this value must be the same used in the `web.xml` `<session-config><session-timeout>` tag and is for checking session expiration
<2> values for password validation
<3> when true, passwords are encrypted in the database
<4> the number of consecutive failed login attempts before an account is locked out
<5> the number of minutes to wait for a locked out account before a new login attempt can be made
<6> the validity time of autologin links
<7> list of roles that users can have

The list of roles defines an id and a key for every role a user can have in the application.
A user can have more than one role.
Role ids are just integer numbers with no special meaning, but they must be unique.
Role keys can be any word that reminds of the activity the user can perform on the site.
In this example, "USER" is any user with no particular privileges, and "ADMIN" is a site administrator.
Role names should be specific to the application domain. For example, a "MANAGER" could handle users, a "GUEST" could have
limited access, a "TEACHER" could see the score editing form.
It's important not to change either the id or the key once the application goes to production because 
these values are stored in the database.

[.todo]
----
- configuration of login/logout/success/failure urls
- configuration of endpoint protection
----

== User Profile

Every web application handles a specific kind of user with different attributes like name, address, age etc.
All user attributes are known as a "user profile".
The Yada Framework provides the `YadaUserProfile` class with basic attributes like `firstName` or `avatar` image.
The web application must subclass it with its own `UserProfile` class in order to add application-specific 
attributes:

[source,java]
----
@Entity
public class UserProfile extends YadaUserProfile {
	@Column(length = 32)
	String nickname; // This is an example of UserProfile customization
----

The user login name is always the email address. Together with the password it is stored in the `userCredentials`
attribute of `YadaUserProfile`, of type `YadaUserCredentials`.

==  Initial user

Usually, in a web application, users either register themselves or are added by an administrator.
In any case, there must be an initial user with administrator rights that is already in the database
when the application starts for the first time.
This can be implemented by subclassing `YadaUserSetup` in any bean, for example a "Setup" bean:

[source,java]
----
@Component
public class Setup extends YadaUserSetup<UserProfile> {
----

Just by doing this, the users defined in the configuration will be created, if not there already,
at each application startup.
This configuration in `conf.webapp.prod.xml` creates one "admin" user (but it doesn't have to be just one):

[source,xml]
----
<config>
	<setup>
		<users>
			<user>
				<nickname>admin</nickname> <!-- This is an example of UserProfile customization -->
				<email>admin@EXAMPLE.com</email>
				<password>changeit</password>
				<locale>en_US</locale>
				<timezone>Europe/Rome</timezone>
				<role>USER</role>
				<role>ADMIN</role>
			</user>
		</users>
	</setup>
----

The xml user definition can contain all attributes defined in the application-specific UserProfile class:
they will be set using reflection.

[TIP]
====
Do not configure a password for production users otherwise
all developers having access to the sources will know the password. If you don't set a password,
you will have to "reset" it the first time you want to log in.
====

To delete all users (for development test):

[source,sql]
----
delete from YadaUserCredentials_roles;
delete yup, yuc FROM YadaUserProfile yup join YadaUserCredentials yuc on yup.userCredentials_id = yuc.id;
----

[TIP]
====
You can create a "secret" production configuration with user setup information by editing the `configuration.xml` file
and adding another `<xml>` entry that points to a local file not committed to git, but you would still have
an unsafe place to store the user passwords
====

==  Password Reset

[.todo]
----
- form to ask password reset
- send password reset email
- form to reset the password
----
 
==  Login page

The login page can either be a full page or a modal, and must contain the login form.

The login form must have a `username` and a `password` field. The form must be submitted 
to the configured `loginProcessingUrl` endpoint via ajax or not depending on how it was opened (see later).

[.todo]
----
- failed attempts lockout message
- login error message
- password reset link
- password reveal button
- force password change after login
----

The login page/modal can either be opened by clicking on a login link or by requesting a protected url: in the
latter case the request (ajax or not) will be saved and replayed after successful login.

[WARNING] 
====
A POST to a protected url that triggers the login process will be replayed as a GET (this is by
Spring Security design) without the original payload. Never allow a post to a protected url unless the user is logged in already. 
====

The login link can either be ajax or normal: 

* Opening a login page with a normal request is trivial
* Opening a modal with a normal request requires landing on some page (usually the home) with a model
parameter that triggers the opening of the embedded login modal
* Opening a login page with an ajax request requires that some element in the page (not the body) has 
the `yadafullPage` class.
* Opening a login modal with an ajax request requires an ajax login link and a controller that returns 
the login modal

The login page/modal is automatically opened when a protected url is requested. The method used (ajax/normal)
to open the login page/modal is the same of the initial request, that is saved for later.
This means that the configured `.formLogin().loginPage` must handle both methods.
This is an example where a normal request opens the home page and triggers the opening of the login modal
by means of a `login` model attribute:

[source,java]
----
@RequestMapping("/loginForm")
public String login(HttpServletRequest request, Model model, Locale locale) {
	boolean loggedIn = yadaSecurityUtil.isLoggedIn();
	if (!yadaWebUtil.isAjaxRequest()) {
		// Normal request
		if (!loggedIn) {
			model.addAttribute("login", "login");
		}
		return home(request, model, locale);
	} else {
		// Ajax request
		if (!loggedIn) {
			return "/modalLogin";
		} else {
			return YadaViews.AJAX_SUCCESS; // Do nothing
		}
	}
}
----

[WARNING] 
====
The login link must not point to the same value configured in `.formLogin().loginPage`.
This is because if a saved request triggers the login process but the user cancels then later
manually performs login, the old saved request would still be used resulting in the wrong page
after login.
The login link must perform a cleanup of the old request with `yadaSecurityUtil.clearAnySavedRequest()`
before opening the login page/modal. 
====

The login link must be shown only when the
user is not logged in and replaced with the logout link otherwise:

[source,html]
----
<header th:with="loggedIn=${@yadaSecurityUtil.loggedIn()}">
	<a th:unless="${loggedIn}" th:href="@{/loginForm}" class="yadaAjax">
		Login
	</a>
	<a th:if="${loggedIn}" th:href="@{/logout}">
		Logout
	</a>
----

The login form must post using the same method (ajax or not) used to load it: if the modal 
containing it was loaded via ajax it must post via ajax, and vice versa.
This is because if the login process is triggered by accessing a protected url in a normal request, the login form
must use a normal POST otherwise the saved request would be redirected to via ajax and may not be shown correctly. 
If, on the contrary, the process is triggered when the initial request is ajax, the login form
must use ajax to POST otherwise the saved request would be loaded non-ajax and shown as a full page.
To achieve this, use the `yadaIsAjaxResponse` model attribute that is always present when returning from
an ajax call:

[source,html]
----
<form th:action="@{/loginPost}" th:classappend="${yadaIsAjaxResponse}?yadaAjax" ... >
----

After successful login, the login modal should be closed and any dynamic parts of the page that differ
when a user is logged in should be replaced with the correct version: for example the login link 
should become a logout link.
The easiest way to do so is to reload the entire page, but this can only be done when there is no
unsaved data that needs to be kept. The `yada.reload()` function should do the trick.
Otherwise, some javascript should fetch the new page parts from the server and replace them 
at the correct position.
In both cases this can be done in a yada:successHandler of the login form:

[source,html]
----
<form th:action="@{/loginPost}" yada:successHandler="postLogin" # <1>
	th:classappend="${yadaIsAjaxResponse}?yadaAjax" 
	role="form" method="post" id="loginForm">
...
<script th:inline="javascript">
    function postLogin() {
    	const headerUrl = /*[[@{/justTheHeader}]]*/ "unset";
    	yada.ajax(headerUrl, null, function(responseText, $responseHtml) {
    		$("header").replaceWith($("header", $responseHtml)); # <2>
    		$("#myLoginModal").modal("hide"); # <3>
    	});
    }
----
<1> postLogin will be called after successful form submission
<2> the current page header is replaced by the header as seen by logged-in users
<3> the login modal is closed
 
Another option would be, after login, to redirect to some other page. This can be done by configuring the
DefaultTargetUrlAjaxRequest with `"/yadaLoginSuccess?targetUrl=/myOtherUrl/"`.

[TIP] 
====
As said above, a public page should not contain a form that posts to a protected endpoint. Such form
should be shown only to logged-in users. This can be done either by conditionally showing the form
or by placing it on a modal that is opened by clicking on a protected link. For example,
a "save icon" could be an ajax link that returns a protected modal containing the save form.
By clicking on the save icon, the user would first trigger the login process then the save form would be shown
in the modal to the now logged-in user.
====

[WARNING] 
====
Never open from a public page a modal containing a form to a protected page using javascript only because
there won't be a chance to trigger the login process.
====

[.todo]
----
- UserProfileDao
- registration controller: registration
- checking session expiration
- autologin
- yadaLoginSuccess?targetUrl: why use it when you have a login successHandler that can do that?
----



